### ISSUE TITLE
Face Tracking not working

### ISSUE THREAD

**Issue by demisquare** [krsbx/mind-ar-ts#2]
Hi, I tried to run the minimal example of mind-ar documentation with your librry and can't run face-tracking cause I get a lot of errors of this type in Console:
`Unhandled Promise Rejection: TypeError: cv.SVDecomp is not a function. (In 'cv.SVDecomp(designMatrixMat, wMat, uMat, vtMat)', 'cv.SVDecomp' is undefined)`

### main.ts
```
import './style.css';

const app = document.querySelector('#app') as unknown as HTMLDivElement;

const SCENE = `
  <a-scene mindar-face embedded vr-mode-ui="enabled: false" device-orientation-permission-ui="enabled: false">
      <a-camera active="false" position="0 0 0"></a-camera>
      <a-entity mindar-face-target="anchorIndex: 1">
        <a-sphere color="green" radius="0.1"></a-sphere>
      </a-entity>
    </a-scene>
`;

app.innerHTML = `
  <h1>Hello Mind AR J/TS!</h1>
  ${SCENE}
`;

app.style.margin = '0';
```

### index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Vite App</title>
    <script type="module" src="./src/face-target/index.ts"></script>
    <script type="module" src="./src/face-target/aframe.ts"></script>

   <!-- I tried both
    <script type="module" src="./out/mindar-face.prod.js"></script>
    <script type="module" src="./out/mindar-face-aframe.prod.js"></script>
    -->
    <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
    <script type="module" src="/src/main.ts"></script>
  </head>
  <style>
    body {
      margin: 0;
    }
  
    .app {
      overflow: hidden;
      position: absolute;
      width: 100%;
      height: 100%;
    }
  </style>
  <body>
    <div id="app" class="app"></div>
  </body>
</html>
```

**Comment by krsbx** [comment]
for this problem, i had the same issue as well and still working on to fix it

most likely it's related to the opencv package that being bundled with this library

can you compile you the opencv.js and see if it works? in my end it can't be compiled at all

if you can compiled it, maybe we can try the opencv that you build instead of the open cv that we use atm

**Comment by demisquare** [comment]
Why don't use this opencv.js already compiled from the official release? https://github.com/opencv/opencv/releases

**Comment by krsbx** [comment]
so `@techstark/opencv-js` is using the official one, but idk for some reason the cv.SVDecomp doesnt define at all

**Comment by demisquare** [comment]
Seems that this version of opencv doesn't have a SVDecomp method, even if the code compiles successfully. I noticed it's not present in the list of available functions in the readme file of the repo.

**Comment by krsbx** [comment]
I try to use the opencv js file that hiukim use in mind-ar-js and try to use it in REPL and it has the SVDecomp function, but when using it to mind-ar-ts it wont build the things

**Comment by demisquare** [comment]
Update: my work colleague and I managed to run the face-tracking module adding hiukim's `opencv.js` file into `@techstark/opencv-js` and editing to some references. I saw techstark/opencv-js#14 and I suggest to wait for the next update, or patch the file in some way.

**Comment by demisquare** [comment]
We had to edit `@techstark/opencv-js`' node-modules' files, so if I want to send you the pull request, you won't see that.

**Comment by krsbx** [comment]
can you explain which file did you guys edit? step by step will be great help, i will think the other way around so we can achieve that without needing to edit the node_modules file

**Comment by demisquare** [comment]
In the opencv.js file had to copy and paste from hiukim's to `@techstark/opencv-js`' the long part starting from `var module...`
Then in `face-target.ts:173`:

`            this.anchorEntities[i].anchorIndex`

becomes:

`            this.anchorEntities[i].targetIndex`

**Comment by demisquare** [comment]
Please check this PR #29.

**Comment by krsbx** [comment]
thank you, the PR is merged now
will continue to work on the geolocation
