### ISSUE TITLE
Image tracking takes forever to target an image

### ISSUE THREAD

**Issue by demisquare** [krsbx/mind-ar-ts#36]
Hi, I'm trying to run the minimal Hiukim's example for image targeting and it doesn't work for some reasons. While the original lib targets the image and renders models instantly, this lib takes a very long time just to run the TargetFound event, or it doesn't run any event at all.

**Comment by krsbx** [comment]
thank you for reporting this, I'll see what's make it slow, also can you share which example did you try? the link to the example would be great

and do you run it in development or in production? I mean are you using the ts file or the build one?

**Comment by demisquare** [comment]
I tried to run both, even in an Angular project and face-target goes well, but image-tracking no. I tried with [this](https://hiukim.github.io/mind-ar-js-doc/examples/minimal) example.

**Comment by krsbx** [comment]
thats weird, in my end its working fine

probably because importing the tensorflow object, let me check what can we do about it

**Comment by krsbx** [comment]
I'll close this issue since the support for the current Image Target will be stop, need to rewrite the Image Target to know which things breaks stuff
