### ISSUE TITLE
face-target occluder doesn't works

### ISSUE THREAD

**Issue by demisquare** [krsbx/mind-ar-ts#37]
Hi, I tried [this](https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/occluder) example with your lib and occluder the face-target won't run at all.

**Comment by krsbx** [comment]
do already try to use a local model instead of the one in cdn?

**Comment by krsbx** [comment]
@demisquare can you try it with a local model instead of using the cdn one and try to use the one inside the experimental folder, you can check the changes of the experimental face-target in this PR #44

**Comment by demisquare** [comment]
I tried with a local file and still the face occluder didn't run. If I add the `mindar-face-occluder` property to `a-gltf-model` tag, the glasses won't show at all in my face.

**Comment by krsbx** [comment]
@demisquare base on the docs of [mind ar itself](https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/occluder), you cant mix the two of them, so if you want to show the glasses model, you need to add the `gltf model` tag for the glasses and another `gltf model` for the occluder

**Comment by krsbx** [comment]
@demisquare did you mix the glasses model with the occluder? when you use `mindar-face-occluder` in `a-gltf-model`, you need to create 2 instance for the `a-gltf-model`, 1 is for the glasses and 1 is for the occluder and please make sure that the anchorIndex for both `a-gltf-model` instance has the same value, by doing this the library will use the face occluder with the same anchorIndex to the other `a-gltf-model` instance as its occluder

**Comment by krsbx** [comment]
you can read it base on the docs in [here](https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/occluder), probably i'll make the docs for this library as well if it has a lot of difference from the original one

**Comment by demisquare** [comment]
I completely forgot that! I always thought if I had added the `mindar-face-occluder` property to the `a-gltf-model` tag I would have enabled the occluder automatically, instead of specifying another model to use as an occluder first.

**Comment by demisquare** [comment]
Today I tried to run the correct scene from the docs and the face-tracker failed to run again due to the cv.SVDecomp error on controller.ts:145.
